bin/demo-run: expect tab separated hosts

diff --git a/bin/run-one b/bin/run-one
--- a/bin/run-one
+++ b/bin/run-one
@@ -5,7 +5,7 @@ required="DOMAIN BOOTSTRAP LISTEN"
 
 for e in $required; do
     [ -z "${!e}" ] && {
-	echo "usage: $required $0 port" 1>&2
+	echo "usage: $required $0" 1>&2
 	exit 2
     }
 done
